services:
  - type: web
    name: wachitraductor-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromGroup: false
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /api
